### ISSUE TITLE
Recent pico-sdk gives many errors.

### ISSUE THREAD

**Issue by kazueda** [notro/gud-pico#3]
Dear Sir,
I tried to build the gud-pico. But the compiler gives many errors. How can I remove these errors? 

/home/kazueda/pico-usbtest/usb_descriptors.c:46:9: error: field name not in record or union initializer
   46 |         .wMaxPacketSize.size = _size,                               \
      |         ^
/home/kazueda/pico-usbtest/usb_descriptors.c:51:5: note: in expansion of macro 'USBTEST_ENDPOINT_DESCRIPTOR'
   51 |     USBTEST_ENDPOINT_DESCRIPTOR(TUSB_XFER_BULK, _addr, CFG_USBTEST_BULK_ENPOINT_SIZE, 0)
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/kazueda/pico-usbtest/usb_descriptors.c:84:16: note: in expansion of macro 'USBTEST_BULK_DESCRIPTOR'
   84 |     .bulk_in = USBTEST_BULK_DESCRIPTOR(0x81),
      |                ^~~~~~~~~~~~~~~~~~~~~~~
/home/kazueda/pico-usbtest/usb_descriptors.c:46:9: note: (near initialization for 'source_sink_config_descriptor.bulk_in')
   46 |         .wMaxPacketSize.size = _size,                               \
      |         ^
/home/kazueda/pico-usbtest/usb_descriptors.c:51:5: note: in expansion of macro 'USBTEST_ENDPOINT_DESCRIPTOR'
   51 |     USBTEST_ENDPOINT_DESCRIPTOR(TUSB_XFER_BULK, _addr, CFG_USBTEST_BULK_ENPOINT_SIZE, 0)
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/kazueda/pico-usbtest/usb_descriptors.c:84:16: note: in expansion of macro 'USBTEST_BULK_DESCRIPTOR'
   84 |     .bulk_in = USBTEST_BULK_DESCRIPTOR(0x81),
      |                ^~~~~~~~~~~~~~~~~~~~~~~
/home/kazueda/pico-usbtest/usb_descriptors.c:46:9: error: field name not in record or union initializer
   46 |         .wMaxPacketSize.size = _size,                               \
      |         ^
/home/kazueda/pico-usbtest/usb_descriptors.c:51:5: note: in expansion of macro 'USBTEST_ENDPOINT_DESCRIPTOR'
   51 |     USBTEST_ENDPOINT_DESCRIPTOR(TUSB_XFER_BULK, _addr, CFG_USBTEST_BULK_ENPOINT_SIZE, 0)
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/kazueda/pico-usbtest/usb_descriptors.c:85:17: note: in expansion of macro 'USBTEST_BULK_DESCRIPTOR'
   85 |     .bulk_out = USBTEST_BULK_DESCRIPTOR(0x01),
      |                 ^~~~~~~~~~~~~~~~~~~~~~~
/home/kazueda/pico-usbtest/usb_descriptors.c:46:9: note: (near initialization for 'source_sink_config_descriptor.bulk_out')
   46 |         .wMaxPacketSize.size = _size,                               \
      |         ^
/home/kazueda/pico-usbtest/usb_descriptors.c:51:5: note: in expansion of macro 'USBTEST_ENDPOINT_DESCRIPTOR'
   51 |     USBTEST_ENDPOINT_DESCRIPTOR(TUSB_XFER_BULK, _addr, CFG_USBTEST_BULK_ENPOINT_SIZE, 0)
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/kazueda/pico-usbtest/usb_descriptors.c:85:17: note: in expansion of macro 'USBTEST_BULK_DESCRIPTOR'
   85 |     .bulk_out = USBTEST_BULK_DESCRIPTOR(0x01),
      |                 ^~~~~~~~~~~~~~~~~~~~~~~
/home/kazueda/pico-usbtest/usb_descriptors.c: In function 'tud_descriptor_string_cb':
/home/kazueda/pico-usbtest/usb_descriptors.c:124:9: warning: converting a packed 'gud_desc_string_t' pointer (alignment 1) to a 'uint16_t' {aka 'const short unsigned int'} pointer (alignment 2) may result in an unaligned pointer value [-Waddress-of-packed-member]
  124 |        cp 
      |         ^~~~~~
/home/kazueda/pico-usbtest/usb_descriptors.c:95:9: note: defined here
   95 | typedef struct TU_ATTR_PACKED
      |         ^~~~~~
/home/kazueda/pico-usbtest/usb_descriptors.c:138:5: warning: converting a packed 'gud_desc_string_t' pointer (alignment 1) to a 'uint16_t' {aka 'const short unsigned int'} pointer (alignment 2) may result in an unaligned pointer value [-Waddress-of-packed-member]
  138 |     return (uint16_t *)&string_descriptor;
      |     ^~~~~~
/home/kazueda/pico-usbtest/usb_descriptors.c:95:9: note: defined here
   95 | typedef struct TU_ATTR_PACKED
      |         ^~~~~~
make[2]: *** [CMakeFiles/usbtest.dir/build.make:90: CMakeFiles/usbtest.dir/usb_descriptors.c.obj] Error 1
make[1]: *** [CMakeFiles/Makefile2:1509: CMakeFiles/usbtest.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

**Comment by notro** [comment]
You say you tried to build gud-pico, but the errors comes from a pico-usbtest build?

**Comment by kazueda** [comment]
Thank you for your reply.  I tried to compile both gud_pico and pico-usbtest sources.
Here is an error message of the gud_pico compiling.

/home/kazueda/gud-pico/libraries/gud_pico/usb_descriptors.c:68:9: error: field name not in record or union initializer
   68 |         .wMaxPacketSize.size = CFG_GUD_BULK_OUT_SIZE,
      |         ^
/home/kazueda/gud-pico/libraries/gud_pico/usb_descriptors.c:68:9: note: (near initialization for 'config_descriptor.bulk_out')
/home/kazueda/gud-pico/libraries/gud_pico/usb_descriptors.c: In function 'tud_descriptor_string_cb':
/home/kazueda/gud-pico/libraries/gud_pico/usb_descriptors.c:96:9: warning: converting a packed 'gud_desc_string_t' pointer (alignment 1) to a 'uint16_t' {aka 'const short unsigned int'} pointer (alignment 2) may result in an unaligned pointer value [-Waddress-of-packed-member]
   96 |         return (uint16_t *)&string_descriptor;
      |         ^~~~~~
/home/kazueda/gud-pico/libraries/gud_pico/usb_descriptors.c:78:9: note: defined here
   78 | typedef struct TU_ATTR_PACKED
      |         ^~~~~~
/home/kazueda/gud-pico/libraries/gud_pico/usb_descriptors.c:124:5: warning: converting a packed 'gud_desc_string_t' pointer (alignment 1) to a 'uint16_t' {aka 'const short unsigned int'} pointer (alignment 2) may result in an unaligned pointer value [-Waddress-of-packed-member]
  124 |     return (uint16_t *)&string_descriptor;
      |     ^~~~~~
/home/kazueda/gud-pico/libraries/gud_pico/usb_descriptors.c:78:9: note: defined here
   78 | typedef struct TU_ATTR_PACKED
      |         ^~~~~~
make[2]: *** [examples/pico-display/CMakeFiles/pico_display.dir/build.make:709: examples/pico-display/CMakeFiles/pico_display.dir/__/__/libraries/gud_pico/usb_descriptors.c.obj] Error 1
make[1]: *** [CMakeFiles/Makefile2:1724: examples/pico-display/CMakeFiles/pico_display.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

**Comment by notro** [comment]
Drop `.size` like this: `.wMaxPacketSize = CFG_GUD_BULK_OUT_SIZE,`
I don't know why it warns about alignment, because all static variables should be 32-bit aligned afaik.
I have some commits locally that has the sdk as a git submodule, but I haven't gotten around to test it properly before I can push it. That avoids problems like that you encountered.

I belive the current gud-pico should build cleanly aganst SDK v1.4.0.

**Comment by kazueda** [comment]
Thank you for your advice.  I succeeded in building revised source and my pico with display could show my linux desktop.

**Comment by foxnux** [comment]
After dropping '.size', I could build gud_pico project against SDK v1.5.1 too.

**Comment by notro** [comment]
Fixed in https://github.com/notro/gud-pico/commit/90439fc47e01349b7a57a3710ddf76cbe937e9c7 and https://github.com/notro/gud-pico/commit/998ce9b197068a8c43bfbdedfb26a41cea4c7927
